# Descrioes das colunas (fonte: Kaggle)
descriptions = {
"x.radius_mean" : "Raio médio das células tumorais",
"x.texture_mean" : "Textura média das células tumorais",
"x.perimeter_mean" : "Perímetro médio das células tumorais",
"x.area_mean" : "Área média das células tumorais",
"x.smoothness_mean" : "Suavidade média das células tumorais",
"x.compactness_mean" : "Compacidade média das células tumorais",
"x.concavity_mean" : "Concavidade média das células tumorais",
"x.concave_points_mean" : "Número médio de porções côncavas do contorno das células tumorais",
"x.symmetry_mean" : "Simetria média das células tumorais",
"x.fractal_dimension_mean" : "aproximação da costa média das células tumorais",
"x.radius_se" : "Erro padrão do raio das células tumorais",
"x.texture_se" : "Erro padrão da textura das células tumorais",
"x.perimeter_se" : "Erro padrão do perímetro das células tumorais",
"x.area_se" : "Erro padrão da área das células tumorais",
"x.smoothness_se" : "Erro padrão da suavidade das células tumorais",
"x.compactness_se" : "Erro padrão da compacidade das células tumorais",
"x.concavity_se" : "Erro padrão da concavidade das células tumorais",
"x.concave_points_se" : "Erro padrão do número de porções côncavas do contorno das células tumorais",
"x.symmetry_se" : "Erro padrão da simetria das células tumorais",
"x.fractal_dimension_se" : "Erro padrão da aproximação da costa das células tumorais",
"x.radius_worst" : "Pior (maior) raio das células tumorais",
"x.texture_worst" : "Pior (mais grave) textura das células tumorais",
"x.perimeter_worst" : "Pior (maior) perímetro das células tumorais",
"x.area_worst" : "Pior (maior) área das células tumorais",
"x.smoothness_worst" : "Pior (mais grave) suavidade das células tumorais",
"x.compactness_worst" : "Pior (mais grave) compactação das células tumorais",
"x.concavity_worst" : "Pior (mais grave) concavidade das células tumorais",
"x.concave_points_worst" : "Pior (mais grave) número de porções côncavas do contorno das células tumorais",
"x.symmetry_worst" : "Pior (mais grave) simetria das células tumorais",
"x.fractal_dimension_worst" : "Pior (mais grave) aproximação da costa das células tumorais",
"y" : "target"
}
len(descriptions)